vim.pack.add({
  {
    src = 'https://github.com/jake-stewart/multicursor.nvim',
  }
})

vim.schedule(function()
  local mc = require("multicursor-nvim")
  mc.setup({});

  vim.api.nvim_set_hl(0, 'MultiCursorCursor', { link = 'Cursor' })
  vim.api.nvim_set_hl(0, 'MultiCursorVisual', { link = 'Visual' })
  vim.api.nvim_set_hl(0, 'MultiCursorDisabledCursor', { link = 'Visual' })
  vim.api.nvim_set_hl(0, 'MultiCursorDisabledVisual', { link = 'Visual' })

  -- override the default esc handler to clear multicursors(if you remove this plugin, this should be set in which-key.lua)
  vim.keymap.set('n', '<esc>', function()
    print 'esc called...'
    if mc.hasCursors() then
      mc.clearCursors()
    end
    vim.cmd 'noh'
  end, { noremap = true })

  vim.keymap.set('n', '<leader>vn', function()
    mc.matchAddCursor(1)
  end, { desc = 'Add cursor and jump to next word' })
  vim.keymap.set('n', '<leader>vN', function()
    mc.matchAddCursor(-1)
  end, { desc = 'Add cursor and jump to prev word' })
  vim.keymap.set('n', '<leader>vs', function()
    mc.matchSkipCursor(1)
  end, { desc = 'Skip cursor and jump to next word' })
  vim.keymap.set('n', '<leader>vS', function()
    mc.matchSkipCursor(-1)
  end, { desc = 'Skip cursor and jump to prev word' })
  vim.keymap.set('n', '<leader>vk', function()
    mc.addCursor('k')
  end, { desc = 'Add cursors above' })
  vim.keymap.set('n', '<leader>vj', function()
    mc.addCursor('j')
  end, { desc = 'Add cursors below' })
  vim.keymap.set('n', '<leader>vl', function()
    mc.nextCursor()
  end, { desc = 'Rotate to next cursor' })
  vim.keymap.set('n', '<leader>vh', function()
    mc.prevCursor()
  end, { desc = 'Rotate to prev cursor' })
  vim.keymap.set('n', '<leader>va', function()
    mc.alignCursors()
  end, { desc = 'Align cursor columns' })
  vim.keymap.set('n', '<leader>vt', function()
    mc.transposeCursors(1)
  end, { desc = 'Rotate visual selection contents' })
  vim.keymap.set('n', '<leader>vT', function()
    mc.transposeCursors(-1)
  end, { desc = 'Rotate visual selection contents (-1)' })
  vim.keymap.set('v', 'S', function()
    mc.splitCursors()
  end, { desc = 'Split cursors' })
  vim.keymap.set('v', 'M', function()
    mc.matchCursors()
  end, { desc = 'Match cursors' })
  vim.keymap.set('v', 'I', function()
    mc.insertVisual()
  end, { desc = 'Insert visual' })
  vim.keymap.set('v', 'A', function()
    mc.appendVisual()
  end, { desc = 'Append visual' })
  vim.keymap.set('v', 'v', function()
    mc.visualToCursors()
  end, { desc = 'Visual to cursors' })
  vim.keymap.set('n', '<leader>vq', function()
    if mc.cursorsEnabled() then mc.disableCursors() else mc.enableCursors() end
  end, { desc = 'Toggle multicursor mode' })
end)
